" VIMRC

" Basics {{{
filetype plugin indent on         " Add filetype, plugin, and indent support
syntax on                         " Turn on syntax highlighting
"}}}

" Variable Assignments {{{
let $MYVIMRC="~/.vim/vimrc"
let $MYVIMDIR="~/.vim"
" }}}

" Settings {{{
set shell=/usr/bin/zsh            " Prefer zsh for shell-related tasks
set grepprg=LC_ALL=C\ grep\ -rns  " Faster ASCII-based grep
set expandtab                     " Prefer spaces over tabs                
set wildcharm=<C-z>               " Macro-compatible command-line wildchar
set path=.,,**                    " Search relative to current file + directory
set tags=./tags;,tags;            " ID Tags relative to current file + directory
set shiftwidth=2                  " Indentation defaults (<< / >> / == / auto)
set shiftround                    " Snap indents via > or < to multiples of sw
set number
" }}}


highlight LineNr term=bold cterm=NONE ctermfg=DarkGrey ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE